# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc3c06b100ead39dbe3eb393c670e4ea90c23450d5da129f45cf6f05eee97b3b77b0cac8eb48509594e7da1c0c22e59efa9b12fa209f8e0a9bbd508d16a2915f

test:
  secret_key_base: 24f91428c2a80aafe2b8974acde89ba5fc055fbb4c5d1880da842d0c9e7575f1fb1972446272f3f9e787e701414c0bd8b2a4b335a088fe91b07c8762bc51e342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
